name: Test Example

on:
  push:
    branches:
      - main

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Use gcloud CLI
        run: gcloud info

